### ISSUE TITLE
Enable Dependabot

### ISSUE THREAD

**Issue by ameukam** [kubernetes-sigs/testgrid#9]
Configure Dependabot for monthly bumps of the node dependencies.

**Comment by ameukam** [comment]
@michelle192837 WDYT ?

**Comment by michelle192837** [comment]
Sg! Dependabot worked pretty well in the other repo to my knowledge 👍

**Comment by michelle192837** [comment]
Made a PR for the monthly updates, and also enabled the security updates. (There are now a bunch of new PRs 😅  I'll take a look through them)
